name: CI/CD
run-name: CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Format code
        run: mvn spotless:apply

      - name: Format check
        run: mvn spotless:check

      - name: Run Tests
        run: mvn test

      - name: Build Docker Image
        run: docker build -t albertoortizortega/travel-agency-kata:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: docker push albertoortizortega/travel-agency-kata:latest

  deploy:
    environment: poc
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: curl https://api.render.com/deploy/srv-cvqpfsp5pdvs738ttvjg?key=1oD2AOwaHWs